bec-project/bec_widgets

bec_widgets/widgets/plots/waveform/settings/curve_settings/curve_tree.py
bec_widgets/widgets/utility/visual/color_button_native/color_button_native.py
bec_widgets/widgets/utility/visual/color_button_native/color_button_native.pyproject
bec_widgets/widgets/utility/visual/color_button_native/color_button_native_plugin.py
bec_widgets/widgets/utility/visual/color_button_native/register_color_button_native.py

Previously as a part of CurveTree widget for curve management of Waveform widget. Can be reused in other widgets as well, plugin created,
closes #573

Independent ColorButton with Native OS dialog.

---

bec_widgets/widgets/containers/layout_manager/layout_manager.py
tests/unit_tests/test_layout_manager.py

Previously, the layout manager would shift **only** the widget to which the new widget was relative.  
For example, if a toolbar was placed at `(0, 0)` and a plotting widget at `(1, 0)`, adding a sidebar to the plot (on the left or right) would shift only the plotting widget.  
This caused the sidebar to appear *under* the toolbar, breaking the intended layout structure.
close #563 
---
https://github.com/user-attachments/assets/db4eecc2-2ca4-4c9e-ab3b-6272c90b92da
---
The layout manager now correctly shifts all affected widgets, preserving the layout logic.
https://github.com/user-attachments/assets/e8efe6fd-1b9c-4767-87ff-55c6f6125240
---
To experiment further with the layout manager, launch the demo app using:
```bash
python layout_manager.py

fix(layout_manager): adding relative widget is shifting whole column to not destroy previous layout

---

.github/workflows/check_pr.yml
.github/workflows/ci.yml
.github/workflows/pytest.yml

- Replace the coverage report comment CI step with uploading a coverage report to Codecov
- Copy the logic from https://github.com/DiamondLightSource/python-copier-template/blob/main/.github/workflows/_check.yml to avoid running workflows for both PR and push when there is a PR for the branch

ci: add codecov upload and skip duplicate steps

---

.github/workflows/check_pr.yml
.github/workflows/ci.yml
.github/workflows/pytest.yml
pyproject.toml

- Don't submit coverage if tests fail
- Tidy up the names of workflows
- Only run expensive test jobs if the linter passes
- Exclude common things (e.g. `TYPE_CHECKING`, `if __name__ == "__main__"`) from coverage by default

Tidy up CI

---

bec_widgets/utils/side_panel.py

A side panel can be added to another widget without the need to specify a toolbar with icons. It can then be triggered programmatically from code and used for purposes such as ROI plots.

fix(side_panel): side panel can be open without icon; toolbar can be hidden if not needed

---

.github/workflows/pytest.yml
pyproject.toml

in https://github.com/bec-project/bec_widgets/commit/01870f9cdaa42cf418740833adeb14a2f014e498 the *regex* `"..."` was excluded from the coverage report, rather than the literal

  ci: include lines with at least three characters in report

---

.github/workflows/pytest.yml

Only track coverage for the source dir - now correctly reported as 77% https://app.codecov.io/gh/bec-project/bec_widgets/pull/600

ci: exclude test dir from coverage report

---

bec_widgets/utils/entry_validator.py

Change in entry validation to use ._info, can be used for validation of nested devices.
closes #570

fix(entry_validator): device signals retrieved from ._info instead of .describe(), close #570

---

.github/workflows/pytest-matrix.yml
.github/workflows/pytest.yml

- uses `uv pip install` instead of `pip install` for setting up the test environment in CI
- looks to save 40-50 seconds per unit test run, regardless of python version, in the `Clone and install dependencies` step, see:
- before: https://github.com/bec-project/bec_widgets/actions/runs/15116995913/job/42490149348
- after: https://github.com/bec-project/bec_widgets/actions/runs/15133079569/job/42538524498

ci: use uv for test env setup

---

.readthedocs.yaml
docs/requirements.txt

Install directly from pulled GH repo instead of pypi

docs: fix build process for sphinx

---

.github/actions/bw_install/action.yml
.github/workflows/ci.yml
.github/workflows/pytest-matrix.yml
.github/workflows/pytest.yml

This pull request introduces a reusable GitHub Action for installing BEC Widgets and related dependencies, and updates multiple workflows (`ci.yml`, `pytest.yml`, and `pytest-matrix.yml`) to use this action. It also enhances the workflows with support for custom branch inputs, improving flexibility and maintainability.
* Created a composite action in `.github/actions/bw_install/action.yml` to handle the installation of BEC Widgets, BEC Core, Ophyd Devices, and their dependencies. This includes setting up Python, checking out repositories, and installing system and Python dependencies.
* Updated `.github/workflows/ci.yml` to:
- Add `workflow_dispatch` support with inputs for specifying branches of BEC Widgets, BEC Core, and Ophyd Devices.
- Pass branch inputs to the `pytest.yml` and …

ci: composite actions for installing BEC Widgets

---

.github/workflows/formatter.yml
bec_widgets/utils/settings_dialog.py
bec_widgets/utils/ui_loader.py

Add a CI formatter step which errors if we import from `PySide6`, except for designer plugins
See before removing such imports: https://github.com/bec-project/bec_widgets/actions/runs/15416417469/job/43380153263
After: https://github.com/bec-project/bec_widgets/actions/runs/15416471105/job/43380326928

ci: check for disallowed imports from PySide

---

bec_widgets/widgets/plots/waveform/settings/curve_settings/curve_tree.py
bec_widgets/widgets/utility/visual/color_button_native/color_button_native.py
tests/unit_tests/test_color_button_native.py

Moves logic of opening color dialog and changing color to `ColorButtonNative`.
closes #681
- Dialog logic moved directly to button
- Test extended
- Open `Waveform` widget with curve dialog and change color of curve

fix(color_button_native): popup logic to choose color moved to ColorButtonNative

---

bec_widgets/cli/client.py
bec_widgets/widgets/plots/image/image.py
bec_widgets/widgets/plots/image/image_base.py
bec_widgets/widgets/plots/image/image_item.py
tests/end-2-end/test_rpc_widgets_e2e.py
tests/unit_tests/test_image_layer.py
tests/unit_tests/test_image_view_next_gen.py

This pull request introduces several changes to improve code clarity, functionality, and testing in the `bec_widgets` package. The most notable updates include the introduction of a new ImageBase class and the renaming the `vrange` property to `v_range` for consistency.
* Moved (likely) shared components into ImageBase class to simplify the development of new image-based widgets, such as the heatmap widget. 
* Renamed the `vrange` property to `v_range` in `bec_widgets/cli/client.py` to improve naming consistency and clarity. Updated both getter and setter methods accordingly. `([bec_widgets/cli/client.pyL1182-R1191](diffhunk://#diff-761d0ac7b2d27daa2c0b873e961ec530e220c7e558c44b9a4c891890d6abcae7L1182-R1191))`
* Added a `FIXME` comment to consider renaming the `parent_image` parameter to …

ImageBase class

---

bec_widgets/cli/client.py
bec_widgets/tests/utils.py
bec_widgets/utils/clickable_label.py
bec_widgets/utils/colors.py
bec_widgets/utils/expandable_frame.py
bec_widgets/utils/forms_from_types/forms.py
bec_widgets/utils/forms_from_types/items.py
bec_widgets/utils/forms_from_types/styles.py
bec_widgets/utils/generate_designer_plugin.py
bec_widgets/widgets/control/scan_control/scan_control.py
bec_widgets/widgets/editors/dict_backed_table.py
bec_widgets/widgets/editors/scan_metadata/_util.py
bec_widgets/widgets/editors/scan_metadata/scan_metadata.py
bec_widgets/widgets/services/device_browser/device_browser.py
bec_widgets/widgets/services/device_browser/device_item/device_item.py
bec_widgets/widgets/services/device_browser/util.py
tests/unit_tests/test_device_browser.py
tests/unit_tests/test_generate_plugin.py
tests/unit_tests/test_generated_form_items.py
tests/unit_tests/test_pydantic_model_form.py
tests/unit_tests/test_scan_metadata.py

Closes #493 
- Adds a dictionary widget type to the generated form
- Adds "pretty display" stylesheet option for disabled generated forms to display config values
- Adds a display for the config to the device browser
For some of the originally proposed features I created #650 instead, which will help towards #495

View device config in device browser

---

bec_widgets/utils/crosshair.py
tests/unit_tests/test_crosshair.py

Fixes bug introduced with new Image base. Currently image items are not holding the monitor info in config, which was fetched for crosshair as identifier. Now it is fetching object name or id. 
- closes #688

fix(crosshair): emitted name from crosshair 2D is objectName of image or its id

---

bec_widgets/widgets/plots/roi/image_roi.py

Fixes bug with wrong reported coordinates. Some code repetition is fixed as well.
-  closes #672
- add roi to some image
- check in roi manager or with rpc that coordinates are corresponding to reality
- try to reverse roi corners and check coordinates after

fix(image_roi): coordinates are emitted correctly when handles are inverted; closes #672

---

bec_widgets/cli/client.py
bec_widgets/widgets/plots/image/image_base.py
bec_widgets/widgets/plots/image/setting_widgets/image_roi_tree.py
bec_widgets/widgets/plots/roi/image_roi.py
tests/unit_tests/test_image_roi_tree.py
tests/unit_tests/test_image_rois.py

Option to disable moving rois by mouse.
- closes #639 
- ROIs can be locked from RPC and during creation
- ROIs can be locked/unlocked through Gui Tree manager in Image widget
- Add some rois to the image widget
- lock/unlock them by GUI or by `roi.movable:bool`

ROI mouse lock/unlock

---

bec_widgets/widgets/containers/main_window/main_window.py

When mouse is move over `QMenu` the app id label will not be lost.
- closes #698

fix(main_window): event filter applied on  QEvent.Type.StatusTip; closes #698

---

bec_widgets/widgets/containers/main_window/addons/scroll_label.py
bec_widgets/widgets/containers/main_window/main_window.py
tests/unit_tests/test_main_widnow.py

Add expiration time from the ClientInfoMessage and fix small bug when you update message to label to not wait for scroll timer.
- closes #705 
- Push some messages with expire time, default is 60s

Scroll Label expire from ClientInfoMessage

---

bec_widgets/tests/utils.py
bec_widgets/widgets/plots/waveform/waveform.py

AsyncSignal can be plotted in the waveform widget
- New decision logic for async devices
- Adjustment of DMMock for unit tests (should be extended with mocked AsyncSignal to test it)
- Add device `waveform` with `waveform_data` (simulation device) to `Waveform` widget 
Not sure how to adjust unit test to reflect AsyncSignals without making import from `ophyd_devices`, I am open to any suggested solution regarding how to adjust unit tests for that. ATM I just added method to `DMMock` which reflects the structure reported by `bec`

fix(waveform): AsyncSignal are handled with the same update mechanism as async readback; closes

---

bec_widgets/applications/launch_window.py
bec_widgets/cli/client.py
bec_widgets/widgets/containers/main_window/main_window.py
bec_widgets/widgets/progress/bec_progressbar/bec_progressbar.py
bec_widgets/widgets/progress/scan_progressbar/register_scan_progress_bar.py
bec_widgets/widgets/progress/scan_progressbar/scan_progress_bar.pyproject
bec_widgets/widgets/progress/scan_progressbar/scan_progress_bar_plugin.py
bec_widgets/widgets/progress/scan_progressbar/scan_progressbar.py
bec_widgets/widgets/progress/scan_progressbar/scan_progressbar.ui
bec_widgets/widgets/progress/scan_progressbar/scan_progressbar_one_line.ui
pyproject.toml
tests/end-2-end/test_rpc_widgets_e2e.py
tests/unit_tests/test_bec_progressbar.py
tests/unit_tests/test_launch_window.py
tests/unit_tests/test_main_widnow.py
tests/unit_tests/test_scan_progress_bar.py

Introduction of new widget ScanProgressBar and implementation into BECMainWindow to bottom right corner.
- closes #709 
- closes #181 
- **new** ScanProgressBar
- **improvement** implementation of ScanProgressBar to BECMainWindow
- adjustments to size policy and resize logic of BECProgressBar
- Launch BEC Gui using BECMainWindow
- Do some scan and see what happens in the bottom right corner.
I had to adjust the number of remaining connections for launcher for turning off lights, better double check the consequences.

Feature/scan progress bar - implementation to BECMainWindow

---

bec_widgets/widgets/plots/waveform/settings/curve_settings/curve_tree.py

Now that the curve tree contains also a combobox for the signal entry, the corresponding combobox must be added to the cleanup. 
I also noticed that the curve tree cleanup manually intercepted the close event and swallowed the cleanup call. I changed it now such that the curve tree also propagates the cleanup call to its parent (BECWidget). The manual interception was not needed IMO. 
closes #730 
- Open the waveform widget, add and remove curve items and close the widget again. The launcher should pop up again.
It's the cleanup in Qt... you never know. None, I hope!

fix(waveform): curve tree elements must clean up signal combobox

---

bec_widgets/cli/client.py
bec_widgets/widgets/containers/dock/dock_area.py
bec_widgets/widgets/editors/sbb_monitor/register_sbb_monitor.py
bec_widgets/widgets/editors/sbb_monitor/sbb_monitor.py
bec_widgets/widgets/editors/sbb_monitor/sbb_monitor_plugin.py

This PR adds a utility widget for displaying the SBB monitor, similar to the one at the gates to PSI West / East. I think for BL scientists and users, this could be a very useful widget. 
SBB provides a unified monitoring tool that can be simply embedded using a url. (I wish more companies would do that!)
- Add new SBBMonitor widget
- Expose the widget through the dock area
- Open the SBBMonitor in designer or DockArea

feat(sbb monitor): add sbb monitor widget

---

tests/unit_tests/test_rpc_server.py

Fixes an issue in the service config test that relies on checking the identity of the config (dictionary) instead of checking for the same content.

test: assert config for equality, not identity

---

bec_widgets/widgets/containers/main_window/addons/notification_center/notification_banner.py
bec_widgets/widgets/containers/main_window/main_window.py
tests/unit_tests/test_notifications.py

Adds a **fully-featured notification centre** to *BECMainWindow*.  
Incoming alarm messages are now displayed as transient toasts with:
* severity-coloured icon and progress bar  
* automatic expiry (configurable)  
* optional manual dismissal  
An always-visible indicator in the status-bar shows live counts per severity and lets the user filter or hide the panel with one click.
- closes #703
- closes #458 
-  **new**  alarm notification system in `BECMainWindow`
- Demo script in python notification_banner.py:
- Click the buttons to raise sample alarms, resize the window, toggle filters, and watch the indicator counts.
- Live in BEC -> Run BEC, trigger test alarms, and confirm that:
-	toasts appear in the top-right of the main window
-	indicator counts update in real time
-	toasts expire …

feat(notification_banner): notification centre for alarms implemented into BECMainWindow

---

bec_widgets/cli/client.py
bec_widgets/widgets/services/device_browser/device_item/device_signal_display.py
bec_widgets/widgets/utility/signal_label/signal_label.py
tests/unit_tests/test_device_browser.py
tests/unit_tests/test_signal_label.py

- don't display `omitted` signals in the `device_signal_display`
- prevents opening this display from waiting for scans as all readings are cached
- prevents refresh from waiting for scans as readings are only from redis

fix(device_signal_display): don't read omitted

---

bec_widgets/cli/rpc/rpc_base.py
bec_widgets/utils/entry_validator.py
tests/end-2-end/test_plotting_framework_e2e.py
tests/unit_tests/test_rpc_base.py

Hotfix for passing `dev.<device>.<signal>` to CLI for plotting for example. Now @rpc_call passes `full_name` instead of `name` for devices and signals.
- closes #792

fix(rpc_base): rpc_call wrapper passes full_name for Devices indeed of name

---

bec_widgets/widgets/control/device_control/positioner_box/_base/positioner_box_base.py
bec_widgets/widgets/control/device_control/positioner_group/positioner_group.py
tests/unit_tests/test_positioner_box.py

This PR fixes an issue of the PositionerBox Base, which resulted in failing to properly handling motors without a precision. 
closes #786 
Please note, if no valid precision (type int) is provided, the fallback for step_size will bei 10**-8 (precision of 8).

Fix handling of none integer values for PositionerBox

---

bec_widgets/widgets/plots/waveform/waveform.py

Autorange was not applied when new curves were added which causes some confusion when newly added curves were outside of the range. Delay has to be applied because pyqtgraph has some problem scalling y axis if curve is not fully rendered.
- closes #810

fix(waveform): autorange is applied with 150ms delay after curve is added

---

bec_widgets/utils/bec_connector.py
bec_widgets/utils/bec_widget.py
bec_widgets/utils/compact_popup.py
bec_widgets/widgets/containers/dock/dock.py
tests/end-2-end/test_rpc_widgets_e2e.py
tests/unit_tests/test_compact_popup_widget.py

This PR removes the cleanup based on a destroyed signal as it proofed to be unreliable and potentially even a cause for segfaults. Instead, the element that receives the close event will not actively call close / deleteLater on all its BECWidget children. 
- Extended cleanup to destroy all child widgets
- Removed cleanup based on the destroyed signal
- Minor change to the e2e test report to more easily find the widgets that haven't been cleaned up
- Run e2e tests
- Open some widgets in designer
- Open the dock area and add / remove docks, maybe even while running scans to put some more load on the system. 
Many... it's Qt. 
Relying on the destroyed signal was for sure the wrong approach. I really hope that this will make it more stable now.

widget cleanup

---

bec_widgets/widgets/plots/waveform/waveform.py

Some scan have `["scan_report_devices"]` empty (timescan etc.) which causes `auto` mode of waveform not determine what should happen. This fix provides mechanism to fallback to index if there is no reported device.

fix(waveform): fallback mechanism for auto mode to use index if scan_report_devices are not available

---

bec_widgets/cli/client_utils.py
tests/unit_tests/test_client_utils.py

This PR fixes an issue that caused multiple guis to be started, even if a GUI with the same ID already exists. 
I also marked `start()` as deprecated as the functionality is fully covered by `show()`. We can update the ipython client in bec once we've merged it. 
- Start the GUI server (default id 'test') and connect with the ipython client using `bec --gui-id test`. It should not start a new GUI, even without specifying the --nogui option.

fix(cli): ensure guis are not started twice

---

bec_widgets/widgets/containers/explorer/collapsible_tree_section.py
bec_widgets/widgets/containers/explorer/explorer.py
bec_widgets/widgets/containers/explorer/script_tree_widget.py
bec_widgets/widgets/utility/ide_explorer/ide_explorer.py
bec_widgets/widgets/utility/ide_explorer/ide_explorer.pyproject
bec_widgets/widgets/utility/ide_explorer/ide_explorer_plugin.py
bec_widgets/widgets/utility/ide_explorer/register_ide_explorer.py
tests/unit_tests/test_explorer.py
tests/unit_tests/test_ide_explorer.py
tests/unit_tests/test_script_tree_widget.py

This PR adds the explorer widget, largely inspired by VSCode's EXPLORER:
It comprises collapsible components that host a title and a sub widget. Explorers can have other explorers as children. On hover, actions are shown. 
A bespoke IDEExplorer widget has been added that implements a bespoke combination for use in the upcoming IDE widget.
related to #800 and #783
[Describe any potential side effects or risks of merging this PR.]
https://github.com/user-attachments/assets/d85e0250-a717-4306-a726-e11fbb328a52
Please note that this PR does not implement a user-ready widget. It merely provides an incremental step towards the IDE view of the general app. At this point, it might be helpful to see the explorer directly in ADS though.

explorer widget

---

.github/workflows/stale-issues.yml

Fix stale issue job's permissions. I also added the option to manually trigger the job through workflow dispatch.

ci: fix stale issues job permissions; add workflow dispatch option

---

bec_widgets/tests/utils.py
bec_widgets/widgets/control/device_control/positioner_box/_base/positioner_box_base.py
bec_widgets/widgets/plots/motor_map/motor_map.py
bec_widgets/widgets/services/device_browser/device_item/device_signal_display.py
bec_widgets/widgets/utility/signal_label/signal_label.py
tests/unit_tests/test_positioner_box.py
tests/unit_tests/test_positioner_box_2d.py

This PR adds the default flag of cached=True to all .read and .read_configuration calls, primarily to make it backward compatible once we change the default. However, it also has the nice side-effect of highlighting when we are using cached readouts.

fix: explicitly pass the cached readout flag
